# Generated by Django 5.0.4 on 2024-04-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_alter_answer_question_alter_answer_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='mission',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='vision',
            field=models.TextField(blank=True, null=True),
        ),
    ]
