# Generated by Django 5.0.4 on 2024-04-25 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0007_alter_admissions_end_date_alter_banner_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admissions',
            options={'ordering': ['id']},
        ),
        migrations.AlterUniqueTogether(
            name='admissions',
            unique_together=set(),
        ),
    ]
