# Generated by Django 5.0.4 on 2024-04-25 09:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0008_alter_admissions_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissions',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
