# Generated by Django 5.0.4 on 2024-04-27 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0009_alter_admissions_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='category',
            field=models.ManyToManyField(blank=True, to='admissions.category'),
        ),
    ]
