# Generated by Django 5.0.4 on 2024-05-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0011_alter_category_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
