# Generated by Django 5.0.4 on 2024-05-02 06:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0012_department_introduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('message', ckeditor.fields.RichTextField()),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
