# Generated by Django 5.0.4 on 2024-05-02 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0013_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
