# Generated by Django 5.0.4 on 2024-05-02 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0016_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.RemoveField(
            model_name='like',
            name='name',
        ),
    ]
