# Generated by Django 5.0.4 on 2024-05-06 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0018_alter_admissions_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated_date',
        ),
        migrations.RemoveField(
            model_name='like',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='like',
            name='updated_date',
        ),
    ]
