# Generated by Django 5.0.4 on 2024-05-06 17:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0020_comment_active_comment_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='introduction',
        ),
        migrations.AddField(
            model_name='department',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
