# Generated by Django 5.0.4 on 2024-05-07 04:03

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0021_remove_department_introduction_department_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
