# Generated by Django 5.0.4 on 2024-05-07 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0022_alter_score_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.RemoveField(
            model_name='question',
            name='name',
        ),
    ]
