# Generated by Django 5.0.4 on 2024-05-08 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0024_faq_email_faq_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={},
        ),
    ]
