# Generated by Django 5.0.4 on 2024-05-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0025_alter_faq_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
